name: Ssense

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: Install libs
        run: bundle install

      - name: Setup environment & Run script
        env:
          USER_AGENT_STRING: ${{ vars.USER_AGENT_STRING }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: ruby sources/ssense.rb sources/ssense/urls.txt
